// <auto-generated />
using System;
using LaytonTempleTours.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LaytonTempleTours.Migrations
{
    [DbContext(typeof(ToursContext))]
    [Migration("20220323055035_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("LaytonTempleTours.Models.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LaytonTempleTours.Models.TimeSlot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppointmentID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateTime = new DateTime(2022, 4, 4, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            DateTime = new DateTime(2022, 4, 4, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            DateTime = new DateTime(2022, 4, 4, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            DateTime = new DateTime(2022, 4, 4, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            DateTime = new DateTime(2022, 4, 4, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            DateTime = new DateTime(2022, 4, 4, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7,
                            DateTime = new DateTime(2022, 4, 4, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8,
                            DateTime = new DateTime(2022, 4, 4, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9,
                            DateTime = new DateTime(2022, 4, 4, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10,
                            DateTime = new DateTime(2022, 4, 4, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11,
                            DateTime = new DateTime(2022, 4, 4, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12,
                            DateTime = new DateTime(2022, 4, 4, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13,
                            DateTime = new DateTime(2022, 4, 5, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14,
                            DateTime = new DateTime(2022, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15,
                            DateTime = new DateTime(2022, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16,
                            DateTime = new DateTime(2022, 4, 5, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17,
                            DateTime = new DateTime(2022, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18,
                            DateTime = new DateTime(2022, 4, 5, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19,
                            DateTime = new DateTime(2022, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20,
                            DateTime = new DateTime(2022, 4, 5, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21,
                            DateTime = new DateTime(2022, 4, 5, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22,
                            DateTime = new DateTime(2022, 4, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23,
                            DateTime = new DateTime(2022, 4, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24,
                            DateTime = new DateTime(2022, 4, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25,
                            DateTime = new DateTime(2022, 4, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26,
                            DateTime = new DateTime(2022, 4, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27,
                            DateTime = new DateTime(2022, 4, 6, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28,
                            DateTime = new DateTime(2022, 4, 6, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29,
                            DateTime = new DateTime(2022, 4, 6, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30,
                            DateTime = new DateTime(2022, 4, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31,
                            DateTime = new DateTime(2022, 4, 6, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32,
                            DateTime = new DateTime(2022, 4, 6, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33,
                            DateTime = new DateTime(2022, 4, 6, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34,
                            DateTime = new DateTime(2022, 4, 6, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35,
                            DateTime = new DateTime(2022, 4, 6, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36,
                            DateTime = new DateTime(2022, 4, 6, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37,
                            DateTime = new DateTime(2022, 4, 7, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38,
                            DateTime = new DateTime(2022, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39,
                            DateTime = new DateTime(2022, 4, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40,
                            DateTime = new DateTime(2022, 4, 7, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 41,
                            DateTime = new DateTime(2022, 4, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 42,
                            DateTime = new DateTime(2022, 4, 7, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 43,
                            DateTime = new DateTime(2022, 4, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 44,
                            DateTime = new DateTime(2022, 4, 7, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 45,
                            DateTime = new DateTime(2022, 4, 7, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 46,
                            DateTime = new DateTime(2022, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 47,
                            DateTime = new DateTime(2022, 4, 7, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 48,
                            DateTime = new DateTime(2022, 4, 7, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 49,
                            DateTime = new DateTime(2022, 4, 8, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 50,
                            DateTime = new DateTime(2022, 4, 8, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 51,
                            DateTime = new DateTime(2022, 4, 8, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 52,
                            DateTime = new DateTime(2022, 4, 8, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 53,
                            DateTime = new DateTime(2022, 4, 8, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 54,
                            DateTime = new DateTime(2022, 4, 8, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 55,
                            DateTime = new DateTime(2022, 4, 8, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 56,
                            DateTime = new DateTime(2022, 4, 8, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 57,
                            DateTime = new DateTime(2022, 4, 8, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 58,
                            DateTime = new DateTime(2022, 4, 8, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 59,
                            DateTime = new DateTime(2022, 4, 8, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 60,
                            DateTime = new DateTime(2022, 4, 8, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 61,
                            DateTime = new DateTime(2022, 4, 9, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 62,
                            DateTime = new DateTime(2022, 4, 9, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 63,
                            DateTime = new DateTime(2022, 4, 9, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 64,
                            DateTime = new DateTime(2022, 4, 9, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 65,
                            DateTime = new DateTime(2022, 4, 9, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 66,
                            DateTime = new DateTime(2022, 4, 9, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 67,
                            DateTime = new DateTime(2022, 4, 9, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 68,
                            DateTime = new DateTime(2022, 4, 9, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 69,
                            DateTime = new DateTime(2022, 4, 9, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 70,
                            DateTime = new DateTime(2022, 4, 9, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 71,
                            DateTime = new DateTime(2022, 4, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 72,
                            DateTime = new DateTime(2022, 4, 9, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
